In [26]:
import numpy as np

In [27]:
a = np.random.randn(5 )


In [29]:
a
##Suppouse we have a as our output of our neural network
## Now we just have to use the softmax algorithm that is exp(a)/ exp(a).sum()
## At least for one sample.....

array([-1.05932654, -0.17511095,  1.17698909, -1.83851134,  0.04917465])

In [4]:
expa = np.exp(a             )

In [5]:
expa

array([ 1.05306477,  3.25611783,  1.07297763,  0.48578391,  1.09381781])

In [6]:
answer = expa / expa.sum()

In [7]:
answer

array([ 0.15126412,  0.46771462,  0.15412444,  0.06977887,  0.15711796])

In [8]:
answer.sum()

1.0

In [9]:
A = np.random.randn(100,5)

# One hunderd samples in 5 classes (k =5)

In [11]:
A
# Remember we will have more than one sample, lets say a 100 
# now we have to compute them all together, let's try the same way we did before

array([[-0.63401943,  2.30819977, -1.19367724,  0.95797959,  0.53893167],
       [-0.24484722,  0.58437228,  0.01316713,  0.51058953,  1.02598631],
       [-0.7574709 ,  1.34313286, -1.63789811,  1.52976202,  0.84022163],
       [ 0.29925008, -0.15856566,  0.47903495,  0.63702193, -0.07924015],
       [-0.06068757,  2.90623395, -1.18373952,  0.55849412,  1.59091375],
       [ 0.06144172,  0.44011592,  0.8265327 , -1.21183825,  0.84803008],
       [-1.2217041 ,  0.23733795,  0.51589934, -0.41775368,  0.0703279 ],
       [ 0.42854357,  1.38114061,  0.21908752,  0.18233461,  0.2926312 ],
       [-2.19996889,  0.90052963,  0.66017111, -0.19404977,  0.6599189 ],
       [ 2.03149332, -0.33994772,  0.47542142,  0.95884046,  1.02873535],
       [ 1.24013001, -1.54492702,  0.28731498, -0.99245261, -0.0920964 ],
       [-0.14827267, -0.53723757,  1.53043029, -0.6774957 ,  0.29579195],
       [-0.2460151 , -0.64405368, -0.35867306,  0.66473999, -0.72989276],
       [ 0.51173246,  0.14881541, -0.4

In [12]:
expA = np.exp(A)
##Calculate de exp of all samples at the same time


In [13]:
expA

array([[  0.53045538,  10.05630466,   0.30310462,   2.6064251 ,
          1.71417459],
       [  0.78282413,   1.79386458,   1.01325419,   1.66627322,
          2.78984576],
       [  0.4688507 ,   3.83102679,   0.1943882 ,   4.61707792,
          2.31688042],
       [  1.3488469 ,   0.85336693,   1.61451556,   1.89084143,
          0.92381804],
       [  0.94111723,  18.28779588,   0.30613181,   1.74803817,
          4.90823175],
       [  1.06336852,   1.55288722,   2.28538089,   0.29764962,
          2.33504248],
       [  0.29472749,   1.26786953,   1.67514435,   0.65852442,
          1.07285991],
       [  1.53502024,   3.97943802,   1.24494023,   1.20001566,
          1.33994852],
       [  0.11080661,   2.46090614,   1.93512342,   0.82361691,
          1.93463542],
       [  7.6254651 ,   0.71180754,   1.60869199,   2.60866985,
          2.79752571],
       [  3.45606275,   0.21332744,   1.33284397,   0.37066647,
          0.91201723],
       [  0.86219598,   0.58436028,   4.620

In [30]:
answer = expA / expA.sum()
## this is wrong. 
#Remember expA is a matrix, not a vector of one sample. 
# In this situation we need to take the sum for every row and divide each element of the row for this sum.
# Remember that exp(a1) / exp(a1) + exp(a2) + exp(a3) + exp(a4) + exp(a5)....exp(ak) !!!

# î is WRONG

In [16]:
answer = expA / expA.sum(axis=1)
##This seems right, but won't work because expA.sum(axis=1) returns a (N,) shape, which will not allow division.

ValueError: operands could not be broadcast together with shapes (100,5) (100,) 

In [17]:
answer = expA / expA.sum(axis=1, keepdims=True)
##By using keepdmins=True attribute, our expA.sum() will return our (N,1) matrix (each row sum of exponentials) 
## and allow us to make the division

In [18]:
answer

array([[ 0.03487437,  0.66114383,  0.01992737,  0.17135737,  0.11269706],
       [ 0.09729283,  0.22294939,  0.12593169,  0.20709177,  0.34673432],
       [ 0.04102568,  0.33522503,  0.01700948,  0.4040066 ,  0.2027332 ],
       [ 0.20340338,  0.128686  ,  0.24346567,  0.28513506,  0.13930989],
       [ 0.03593242,  0.69823894,  0.01168829,  0.06674114,  0.18739921],
       [ 0.14113646,  0.20610824,  0.30332907,  0.03950579,  0.30992044],
       [ 0.05931174,  0.25514942,  0.33711048,  0.1325232 ,  0.21590517],
       [ 0.16506725,  0.42792589,  0.13387371,  0.12904279,  0.14409036],
       [ 0.01525193,  0.33873037,  0.26635924,  0.1133664 ,  0.26629207],
       [ 0.49670307,  0.0463653 ,  0.10478603,  0.16992201,  0.18222359],
       [ 0.54989784,  0.03394276,  0.21207023,  0.05897714,  0.14511204],
       [ 0.10887965,  0.07379406,  0.58344261,  0.06413692,  0.16974677],
       [ 0.17643904,  0.11850283,  0.15764055,  0.43866258,  0.10875501],
       [ 0.26230755,  0.18247271,  0.1

In [19]:
answer.sum(axis=1)
##check if the sum of every row of our answer is 1 as we are talking about probabilities

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
expA.sum(axis=1, keepdims=True)
##See the value of how much we are dividing every row

array([[ 15.21046435],
       [  8.04606188],
       [ 11.42822402],
       [  6.63138886],
       [ 26.19131485],
       [  7.53432873],
       [  4.96912569],
       [  9.29936267],
       [  7.2650885 ],
       [ 15.35216018],
       [  6.28491785],
       [  7.91879846],
       [  4.43161809],
       [  6.35962928],
       [  5.24421868],
       [ 12.46061721],
       [  5.03138341],
       [ 14.01603795],
       [  4.56763865],
       [  9.2891493 ],
       [  6.07576512],
       [  7.55073239],
       [  3.00501816],
       [  4.45030857],
       [ 13.94406158],
       [  4.36555937],
       [ 15.80860667],
       [  6.39039206],
       [  4.73413313],
       [  5.37455847],
       [ 12.18133921],
       [  6.4735615 ],
       [  5.64949595],
       [  6.99245728],
       [ 24.61456827],
       [  5.13549923],
       [  4.88391224],
       [ 11.51297544],
       [ 13.61973533],
       [  5.27592111],
       [  8.11956173],
       [  4.15965049],
       [  9.40250364],
       [  8

In [25]:
expA.sum(axis=1, keepdims=True).shape

(100, 1)